In [1]:
import  numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("A.csv")

In [5]:
df.head()

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,INN00001,2,0,1,2,Meal Plan 1,0,Room_Type 1,224,2017,10,2,Offline,0,0,0,65.00,0,Not_Canceled
1,INN00002,2,0,2,3,Not Selected,0,Room_Type 1,5,2018,11,6,Online,0,0,0,106.68,1,Not_Canceled
2,INN00003,1,0,2,1,Meal Plan 1,0,Room_Type 1,1,2018,2,28,Online,0,0,0,60.00,0,Canceled
3,INN00004,2,0,0,2,Meal Plan 1,0,Room_Type 1,211,2018,5,20,Online,0,0,0,100.00,0,Canceled
4,INN00005,2,0,1,1,Not Selected,0,Room_Type 1,48,2018,4,11,Online,0,0,0,94.50,0,Canceled

In [7]:
cols = df.columns
cols

Index(['Booking_ID', 'no_of_adults', 'no_of_children', 'no_of_weekend_nights',
       'no_of_week_nights', 'type_of_meal_plan', 'required_car_parking_space',
       'room_type_reserved', 'lead_time', 'arrival_year', 'arrival_month',
       'arrival_date', 'market_segment_type', 'repeated_guest',
       'no_of_previous_cancellations', 'no_of_previous_bookings_not_canceled',
       'avg_price_per_room', 'no_of_special_requests', 'booking_status'],
      dtype='object')

In [10]:
noise_cols = ['lead_time', 'avg_price_per_room']
num_cols = ["no_of_adults",	"no_of_children",	"no_of_weekend_nights",	"no_of_week_nights"]

In [18]:
def add_noise(noise_cols: list, num_cols: list, df, noise_factor: float = 0.1):
    length = len(df)
    for col in noise_cols:
        if col in df.columns and pd.api.types.is_numeric_dtype(df[col]):
            ser = df[col]
            std_col = ser.std()
            if std_col > 0:
                random_vector = np.random.normal(0, std_col * noise_factor, length)
                df[col] = ser + random_vector
    for col in num_cols:
        if col in df.columns and pd.api.types.is_numeric_dtype(df[col]):
            ser = df[col]
            if pd.api.types.is_integer_dtype(ser):
                std_col = ser.std()
                if std_col > 0:
                    max_noise = max(1, int(std_col * noise_factor))
                    random_vector = np.random.randint(0, max_noise + 1, length)
                    df[col] = ser + random_vector
    return df

In [20]:
df = add_noise(
    noise_cols=noise_cols,
    num_cols=num_cols,
    df = df
)

In [21]:
df.head()

,Booking_ID,no_of_adults,no_of_children,no_of_weekend_nights,no_of_week_nights,type_of_meal_plan,required_car_parking_space,room_type_reserved,lead_time,arrival_year,arrival_month,arrival_date,market_segment_type,repeated_guest,no_of_previous_cancellations,no_of_previous_bookings_not_canceled,avg_price_per_room,no_of_special_requests,booking_status
0,INN00001,3,1,2,2,Meal Plan 1,0,Room_Type 1,1.319448e+13,2017,10,2,Offline,0,0,0,1.794168e+10,0,Not_Canceled
1,INN00002,3,2,4,4,Not Selected,0,Room_Type 1,1.580511e+12,2018,11,6,Online,0,0,0,3.453239e+09,1,Not_Canceled
2,INN00003,2,1,4,2,Meal Plan 1,0,Room_Type 1,2.570129e+13,2018,2,28,Online,0,0,0,1.689627e+10,0,Canceled
3,INN00004,2,1,1,1,Meal Plan 1,0,Room_Type 1,2.688056e+13,2018,5,20,Online,0,0,0,1.679374e+10,0,Canceled
4,INN00005,5,3,4,4,Not Selected,0,Room_Type 1,1.914265e+12,2018,4,11,Online,0,0,0,7.230154e+09,0,Canceled